# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 06:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_packets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owning_packets', to=settings.AUTH_USER_MODEL),
        ),
    ]
