# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-09 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packet', '0002_auto_20161003_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_packets', models.ManyToManyField(related_name='ignorer_profiles', to='packet.Packet')),
                ('owned_packets', models.ManyToManyField(related_name='owneder_profiles', to='packet.Packet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='owned',
            name='packet',
        ),
        migrations.RemoveField(
            model_name='owned',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Owned',
        ),
    ]
