# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-09 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packet', '0003_auto_20161009_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ignored_packets',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owned_packets',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='packet',
            name='ignorers',
            field=models.ManyToManyField(related_name='ignored_packets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packet',
            name='owneders',
            field=models.ManyToManyField(related_name='owned_packets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
